# Generated by Django 5.2.3 on 2025-06-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_aogirichannel_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('episode', models.CharField(max_length=50)),
                ('view_count', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('publish_time', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
