# Generated by Django 5.2.3 on 2025-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_animecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('img', models.URLField()),
                ('num', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='animecard',
            name='publish_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animecard',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
